#!/usr/bin/env ruby

filein = ARGV[0]
fileout = filein.split(".")[0] + ".rb"

system "ruby ./lib/compile.rb #{filein}"
unless $?.exitstatus == 0
  puts "ERROR: error on score compile of #{filein}"
  exit
end
system "ruby #{fileout}"
unless $?.exitstatus == 0
  puts "ERROR: on rendering compiled score #{fileout}"
  exit
end
puts `rm #{fileout}`
