lib_path = "./lib"

require "wavefile"
require "#{lib_path}/sample"
require "#{lib_path}/sound"
require "#{lib_path}/effect"
require "#{lib_path}/compound"
require "#{lib_path}/freq_file"
require "#{lib_path}/freq_wave"
require "#{lib_path}/freq_sum"
require "#{lib_path}/pitch_set"
require "#{lib_path}/rest"
require "#{lib_path}/sound_factory"
require "#{lib_path}/stream"
require "#{lib_path}/wav_sampler"
require "#{lib_path}/wave_form"
require "#{lib_path}/lib"
